# Created using ChatGPT
# Taken from https://github.com/AldenizenMC/AldenizenMC.github.io/blob/main/.github/workflows/update-version.yml
name: increment version query parameter

on:
    push:
        paths:
            - "**/*.css"
            - "**/*.js"
    workflow_dispatch:

jobs:
    increment_version:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Run Python script
              run: |
                  python scripts/update_version.py

            - name: Commit changes
              run: |
                  git config --global user.name "github-actions"
                  git config --global user.email "github-actions@users.noreply.github.com"
                  git commit -am "Incremented version query parameter"

            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: ${{ github.ref }}
