name: increment version query parameter

on:
    push:
        branches:
            - main
    pull_request:
        types:
            - synchronize

jobs:
    increment_version:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Determine file changes
              id: file_changes
              run: |
                  echo "::set-output name=has_changes::$(git diff-tree --no-commit-id --name-only -r ${{ github.event.pull_request.head.sha }})"

            - name: Run Python script
              if: steps.file_changes.outputs.has_changes == 'true' && contains(github.event.pull_request.changed_files, '*.css') || contains(github.event.pull_request.changed_files, '*.js')
              run: |
                  python scripts/update_version.py

            - name: Commit changes
              run: |
                  git config --global user.name "github-actions"
                  git config --global user.email "github-actions@users.noreply.github.com"
                  git commit -am "Incremented version query parameter"

            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: ${{ github.ref }}
